plugins {
    id 'dev.architectury.loom'
}

base {
    archivesName = rootProject.name + '-fabric'
}

loom {
    silentMojangMappingsLicense()
    mixin {
        defaultRefmapName = "lanplus.refmap.json"
    }
    mods {
        lanplus {
            sourceSet sourceSets.main
            sourceSet project(':common').sourceSets.main
        }
    }
}

jar {
    from project(':common').sourceSets.main.output
}

dependencies {
    implementation project(path: ':common', configuration: 'namedElements')
    runtimeOnly project(':common').sourceSets.main.output
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
}

processResources {
    var replaceProperties = [
            minecraft_version       : rootProject.minecraft_version,
            minecraft_version_range : rootProject.minecraft_version_range,
            fabric_minecraft_version_range : rootProject.fabric_minecraft_version_range,
            mod_id                  : rootProject.mod_id,
            mod_name                : rootProject.mod_name,
            mod_license             : rootProject.mod_license,
            mod_version             : rootProject.mod_version,
            mod_authors             : rootProject.mod_authors,
            mod_description         : rootProject.mod_description,
            mod_display_url         : rootProject.mod_display_url,
            mod_issue_tracker_url   : rootProject.mod_issue_tracker_url,
    ]
    inputs.properties replaceProperties
    filesMatching(['fabric.mod.json']) {
        expand replaceProperties + [project: project]
    }
}

java {
    withSourcesJar()
}
