plugins {
    id 'dev.architectury.loom'
}

base {
    archivesName = rootProject.name + '-forge'
}

loom {
    silentMojangMappingsLicense()
    forge {
        mixinConfig "${rootProject.mod_id}.mixins.json"
    }
}

dependencies {
    implementation project(path: ':common', configuration: 'namedElements')
    forge "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}"
}

processResources {
    var replaceProperties = [
            minecraft_version       : rootProject.minecraft_version,
            minecraft_version_range : rootProject.minecraft_version_range,
            forge_version           : rootProject.forge_version,
            forge_version_range     : rootProject.forge_version_range,
            loader_version_range    : rootProject.loader_version_range,
            mod_id                  : rootProject.mod_id,
            mod_name                : rootProject.mod_name,
            mod_license             : rootProject.mod_license,
            mod_version             : rootProject.mod_version,
            mod_authors             : rootProject.mod_authors,
            mod_description         : rootProject.mod_description,
            mod_display_url         : rootProject.mod_display_url,
            mod_issue_tracker_url   : rootProject.mod_issue_tracker_url,
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

java {
    withSourcesJar()
}
