plugins {
    id 'dev.architectury.loom'
}

base {
    archivesName = rootProject.name + '-common'
}

loom {
    silentMojangMappingsLicense()
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.officialMojangMappings()

}

java {
    withSourcesJar()
}
